import {lendingConfig} from "./config";import {assertCents,simpleInterestCents} from "./money";
export const LOAN_STATES=["DRAFT","ELIGIBILITY_PENDING","OFFERED","ACCEPTED","DISBURSEMENT_PENDING","ACTIVE","REPAID","DECLINED","CANCELED","DISBURSEMENT_FAILED","PAST_DUE","DEFAULTED","WRITTEN_OFF"] as const;export type LoanState=typeof LOAN_STATES[number];
const transitions:Record<LoanState,readonly LoanState[]>={DRAFT:["ELIGIBILITY_PENDING","CANCELED"],ELIGIBILITY_PENDING:["OFFERED","DECLINED","CANCELED"],OFFERED:["ACCEPTED","CANCELED"],ACCEPTED:["DISBURSEMENT_PENDING","CANCELED"],DISBURSEMENT_PENDING:["ACTIVE","DISBURSEMENT_FAILED"],ACTIVE:["REPAID","PAST_DUE"],PAST_DUE:["REPAID","DEFAULTED"],DEFAULTED:["REPAID","WRITTEN_OFF"],DECLINED:[],CANCELED:[],DISBURSEMENT_FAILED:[],REPAID:[],WRITTEN_OFF:[]};
export const canTransition=(from:LoanState,to:LoanState)=>transitions[from].includes(to);
export type LoanOffer={principalCents:number;aprBps:number;interestCents:number;feeCents:number;totalRepaymentCents:number;termDays:number};
export function createLoanOffer(principalCents:number):LoanOffer{assertCents(principalCents,"principalCents");if(principalCents<100)throw new Error("Minimum sandbox loan is $1.00");if(principalCents>lendingConfig.maxLoanCents)throw new Error("Requested principal exceeds the configured maximum");const interestCents=simpleInterestCents(principalCents,lendingConfig.aprBps,lendingConfig.termDays);return{principalCents,aprBps:lendingConfig.aprBps,interestCents,feeCents:0,totalRepaymentCents:principalCents+interestCents,termDays:lendingConfig.termDays};}
export type CapitalState={totalCapitalCents:number;reservedCents:number;outstandingPrincipalCents:number;lendingPaused:boolean};
export function availableToOriginate(state:CapitalState){return Math.max(0,state.totalCapitalCents-state.reservedCents-state.outstandingPrincipalCents-lendingConfig.minimumReserveCents);}
export function assertCanOriginate(state:CapitalState,principalCents:number,hasActiveLoan:boolean){if(!lendingConfig.lendingEnabled||state.lendingPaused)throw new Error("New lending is currently paused");if(hasActiveLoan)throw new Error("Borrower already has an active loan");if(principalCents>lendingConfig.maxLoanCents)throw new Error("Loan exceeds maximum allowed principal");if(principalCents>availableToOriginate(state))throw new Error("Not enough available lending capital");}
